# Generated by Django 5.0.2 on 2024-03-14 11:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_habit_userid_remove_task_checked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='id_habit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='habit',
            unique_together={('hour',)},
        ),
    ]
