# Generated by Django 5.0.2 on 2024-04-22 02:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_habit_user_id_task_user_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="habit",
            unique_together={("user_id", "hour")},
        ),
    ]
