# Generated by Django 5.0.6 on 2024-05-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_alter_habit_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="calendar_id",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="habit",
            name="hour_end",
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="calendar_id",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="hour_end",
            field=models.TimeField(null=True),
        ),
    ]
